// eslint-disable-next-line import/no-extraneous-dependencies

const fakeResult = [
  {
    description: '\n      A terminal-based presentation tool with colors and effects.\n    ',
    is_favorite: 1,
    language: 'Python',
    link: 'https://github.com/vinayak-mehta/present',
    message_id: 30,
    repository: '/vinayak-mehta/present',
    star: '\n        1,649\n',
  },
  {
    description: '\n      DearPyGui: A GPU Accelerated Python GUI Framework\n    ',
    is_favorite: 1,
    language: 'C++',
    link: 'https://github.com/hoffstadt/DearPyGui',
    message_id: 78,
    repository: '/hoffstadt/DearPyGui',
    star: '\n        1,184\n',
  },
  {
    description: '\n      Matplot++: A C++ Graphics Library for Data Visualization ',
    is_favorite: 0,
    language: 'C++',
    link: 'https://github.com/alandefreitas/matplotplusplus',
    message_id: 77,
    repository: '/alandefreitas/matplotplusplus',
    star: '\n        1,018\n',
  },
  {
    description: '\n      All Algorithms implemented in Python\n    ',
    is_favorite: 1,
    language: 'Python',
    link: 'https://github.com/TheAlgorithms/Python',
    message_id: 76,
    repository: '/TheAlgorithms/Python',
    star: '\n        83,197\n',
  },
  {
    description: '\n      WebRTC for the Curious: Go beyond the APIs\n    ',
    is_favorite: 0,
    language: null,
    link: 'https://github.com/webrtc-for-the-curious/webrtc-for-the-curious',
    message_id: 75,
    repository: '/webrtc-for-the-curious/webrtc-for-the-curious',
    star: '\n        349\n',
  },
  {
    description: '\n      \n',
    is_favorite: 0,
    language: 'Python',
    link: 'https://github.com/trekhleb/learn-python',
    message_id: 74,
    repository: '/trekhleb/learn-python',
    star: '\n        4,645\n',
  },
  {
    description: '\n      \n',
    is_favorite: 0,
    language: null,
    link: 'https://github.com/EbookFoundation/free-programming-books',
    message_id: 73,
    repository: '/EbookFoundation/free-programming-books',
    star: '\n        157,757\n',
  },
  {
    description: '\n      Roadmap to becoming a web developer in 2020\n    ',
    is_favorite: 0,
    language: null,
    link: 'https://github.com/kamranahmedse/developer-roadmap',
    message_id: 72,
    repository: '/kamranahmedse/developer-roadmap',
    star: '\n        122,187\n',
  },
  {
    description: '\n      An extension for VS Code that visualizes data during debugging.\n    ',
    is_favorite: 0,
    language: 'TypeScript',
    link: 'https://github.com/hediet/vscode-debug-visualizer',
    message_id: 71,
    repository: '/hediet/vscode-debug-visualizer',
    star: '\n        4,411\n',
  },
  {
    description: '\n      Official open source SVG icon library for Bootstrap.\n    ',
    is_favorite: 0,
    language: 'JavaScript',
    link: 'https://github.com/twbs/icons',
    message_id: 70,
    repository: '/twbs/icons',
    star: '\n        2,788\n',
  },
  {
    description: '\n      \n',
    is_favorite: 0,
    language: 'Kotlin',
    link: 'https://github.com/airbnb/Showkase',
    message_id: 69,
    repository: '/airbnb/Showkase',
    star: '\n        459\n',
  },
  {
    description: null,
    is_favorite: 0,
    language: 'JavaScript',
    link: 'https://github.com/LetsUpgrade/Javascript-Essentials',
    message_id: 68,
    repository: '/LetsUpgrade/Javascript-Essentials',
    star: '\n        181\n',
  },
  {
    description: '\n      A set of best practices for JavaScript projects\n    ',
    is_favorite: 0,
    language: 'JavaScript',
    link: 'https://github.com/elsewhencode/project-guidelines',
    message_id: 67,
    repository: '/elsewhencode/project-guidelines',
    star: '\n        22,346\n',
  },
  {
    description: '\n      \n',
    is_favorite: 0,
    language: 'Solidity',
    link: 'https://github.com/sushiswap/sushiswap',
    message_id: 66,
    repository: '/sushiswap/sushiswap',
    star: '\n        75\n',
  },
  {
    description:
      '\n      Python library for converting Python calculations into rendered latex.\n    ',
    is_favorite: 0,
    language: 'Python',
    link: 'https://github.com/connorferster/handcalcs',
    message_id: 65,
    repository: '/connorferster/handcalcs',
    star: '\n        1,007\n',
  },
  {
    description: '\n      Rust explained using easy English\n    ',
    is_favorite: 0,
    language: 'Shell',
    link: 'https://github.com/Dhghomon/easy_rust',
    message_id: 64,
    repository: '/Dhghomon/easy_rust',
    star: '\n        4,515\n',
  },
  {
    description: null,
    is_favorite: 0,
    language: null,
    link: 'https://github.com/OfJAAH/KingOfBugBountyTips',
    message_id: 63,
    repository: '/OfJAAH/KingOfBugBountyTips',
    star: '\n        162\n',
  },
  {
    description: '\n      The all-in-one Red Team extension for Web Pentester ',
    is_favorite: 0,
    language: 'JavaScript',
    link: 'https://github.com/LasCC/Hack-Tools',
    message_id: 62,
    repository: '/LasCC/Hack-Tools',
    star: '\n        190\n',
  },
  {
    description: '\n      Some Tutorials and Things to Do while Hunting That Vulnerability.\n    ',
    is_favorite: 0,
    language: null,
    link: 'https://github.com/KathanP19/HowToHunt',
    message_id: 61,
    repository: '/KathanP19/HowToHunt',
    star: '\n        92\n',
  },
  {
    description: '\n      \n',
    is_favorite: 0,
    language: 'Go',
    link: 'https://github.com/halfrost/LeetCode-Go',
    message_id: 60,
    repository: '/halfrost/LeetCode-Go',
    star: '\n        5,168\n',
  },
  {
    description: '\n      Jupyter notebooks for teaching/learning Python 3\n    ',
    is_favorite: 0,
    language: 'Python',
    link: 'https://github.com/jerry-git/learn-python3',
    message_id: 59,
    repository: '/jerry-git/learn-python3',
    star: '\n        2,225\n',
  },
  {
    description:
      '\n      Collection of 8000+ publicly available IPTV channels from all over the world\n    ',
    is_favorite: 0,
    language: 'JavaScript',
    link: 'https://github.com/iptv-org/iptv',
    message_id: 58,
    repository: '/iptv-org/iptv',
    star: '\n        19,335\n',
  },
  {
    description: '\n      Script to remove Windows 10 bloatware.\n    ',
    is_favorite: 0,
    language: 'PowerShell',
    link: 'https://github.com/Sycnex/Windows10Debloater',
    message_id: 57,
    repository: '/Sycnex/Windows10Debloater',
    star: '\n        6,454\n',
  },
  {
    description: '\n      Curated list of project-based tutorials\n    ',
    is_favorite: 0,
    language: null,
    link: 'https://github.com/tuvtran/project-based-learning',
    message_id: 56,
    repository: '/tuvtran/project-based-learning',
    star: '\n        36,290\n',
  },
  {
    description:
      '\n      Learn to Code While Building Apps - The Complete Flutter Development Bootcamp\n    ',
    is_favorite: 0,
    language: null,
    link: 'https://github.com/londonappbrewery/Flutter-Course-Resources',
    message_id: 55,
    repository: '/londonappbrewery/Flutter-Course-Resources',
    star: '\n        5,418\n',
  },
];

export default {
  'GET  /api/items/github': fakeResult,
};
