// eslint-disable-next-line import/no-extraneous-dependencies

const fakeResult = [
  {
    comments: '257 comments',
    id: 106,
    link: 'https://www.buzzfeednews.com/article/peteraldhous/hackers-gedmatch-dna-privacy',
    points: '451 points',
    title: 'Breach exposed more than one million DNA profiles on a major genealogy database',
  },
  {
    comments: '31 comments',
    id: 107,
    link: 'https://1secondpainting.com/',
    points: '107 points',
    title: '1SecondPainting: Generate abstract paintings in one click',
  },
  {
    comments: '124 comments',
    id: 108,
    link: 'https://kde.slimbook.es/',
    points: '222 points',
    title: 'KDE Slimbook: Linux Laptop with Ryzen 4000',
  },
  {
    comments: '64 comments',
    id: 109,
    link:
      'https://www.buzzfeednews.com/article/janelytvynenko/instacart-customers-info-sold-online',
    points: '267 points',
    title: 'The personal info of what could be Instacart customers is being sold online',
  },
  {
    comments: '20 comments',
    id: 110,
    link: 'https://www.concerthotels.com/worlds-greatest-vocal-ranges',
    points: '42 points',
    title: 'The vocal ranges of the greatest artists of all time',
  },
  {
    comments: '8 comments',
    id: 111,
    link: 'https://www.youtube.com/watch?v=P-2P3MSZrBM',
    points: '60 points',
    title: 'Joscha Bach: Artificial Consciousness and the Nature of Reality [video]',
  },
  {
    comments: '13 comments',
    id: 112,
    link: 'https://ai.facebook.com/blog/deep-learning-to-translate-between-programming-languages',
    points: '46 points',
    title: 'Deep learning to translate between programming languages',
  },
  {
    comments: '2 comments',
    id: 113,
    link: 'https://ts.data61.csiro.au/publications/csiroabstracts/Heiser_20.abstract.pml',
    points: '104 points',
    title: 'Verified seL4 on secure RISC-V processors',
  },
  {
    comments: '77 comments',
    id: 114,
    link: 'https://github.com/propjockey/css-sweeper#readme',
    points: '332 points',
    title: 'Show HN: MineSweeper implemented in 100% CSS and HTML – no JavaScript',
  },
  {
    comments: '6 comments',
    id: 115,
    link: 'https://bitwarden.com/blog/post/bitwarden-network-security-assessment-2020/',
    points: '26 points',
    title: 'Bitwarden second security audit report',
  },
  {
    comments: '35 comments',
    id: 116,
    link: 'https://react-guitar.com',
    points: '196 points',
    title: 'Show HN: React Guitar – A guitar component for React',
  },
  {
    comments: '25 comments',
    id: 117,
    link: 'https://github.com/Dhghomon/easy_rust',
    points: '122 points',
    title: 'Rust explained using easy English',
  },
  {
    comments: '57 comments',
    id: 118,
    link:
      'https://blogs.sciencemag.org/pipeline/archives/2020/07/15/new-data-on-t-cells-and-the-coronavirus',
    points: '133 points',
    title: 'New Data on T Cells and the Coronavirus',
  },
  {
    comments: '33 comments',
    id: 119,
    link: 'https://lwn.net/op/AuthorGuide.lwn',
    points: '144 points',
    title: 'LWN pays $300 for a well-written article from new authors',
  },
  {
    comments: '12 comments',
    id: 120,
    link:
      'https://www.npr.org/sections/coronavirus-live-updates/2020/07/22/894049653/one-third-of-u-s-museums-may-not-survive-the-year-survey-finds',
    points: '48 points',
    title: 'One-Third of U.S. Museums May Not Survive the Year, Survey Finds',
  },
  {
    comments: '18 comments',
    id: 121,
    link: 'https://staysaasy.com/management/2020/07/07/dont-create-chaos.html',
    points: '56 points',
    title: "Don't Create Chaos",
  },
  {
    comments: '24 comments',
    id: 122,
    link: 'https://blog.lasseter.org/posts/2020/07/terminal-server-on-a-budget/',
    points: '49 points',
    title: 'Terminal Server on a Budget',
  },
  {
    comments: '23 comments',
    id: 123,
    link: 'https://lwn.net/SubscriberLink/826456/2ea90dd464e104d5/',
    points: '121 points',
    title: 'New Features in Gnuplot 5.4',
  },
  {
    comments: '30 comments',
    id: 124,
    link: 'https://thevalley.substack.com/p/understand-seed-rounds-dynamics-in',
    points: '83 points',
    title: 'Understand seed round dynamics in Silicon Valley',
  },
  {
    comments: '82 comments',
    id: 125,
    link:
      'https://www.quantamagazine.org/mathematicians-discover-the-perfect-way-to-multiply-20190411/',
    points: '229 points',
    title: 'Mathematicians discover a perfect way to multiply (2019)',
  },
  {
    comments: '37 comments',
    id: 126,
    link: 'http://www.flashgamehistory.com/',
    points: '105 points',
    title: 'Flash Game History',
  },
  {
    comments: '4 comments',
    id: 127,
    link: 'https://gvv.mpi-inf.mpg.de/projects/XNect/',
    points: '17 points',
    title: 'XNect: Real-Time Multi-Person 3D Motion Capture with a Single RGB Camera',
  },
  {
    comments: '20 comments',
    id: 128,
    link: 'https://www.ancientmedicine.org/home/2018/3/11/aristotles-lost-book-on-magic',
    points: '74 points',
    title: "Aristotle's Lost Book on Magic (2018)",
  },
  {
    comments: '49 comments',
    id: 129,
    link: 'https://tinkeredthinking.com/index.php?id=841',
    points: '129 points',
    title: "What is GPT-3? written in layman's terms",
  },
  {
    comments: '144 comments',
    id: 130,
    link: 'https://www.eso.org/public/news/eso2011/?lang',
    points: '607 points',
    title: 'First Ever Image of a Multi-Planet System Around a Sun-Like Star Captured by ESO',
  },
  {
    comments: '11 comments',
    id: 131,
    link: 'https://hardfork.substack.com/p/why-most-founders-dont-take-good',
    points: '26 points',
    title: 'Why Most Founders Don’t Take Good Advice',
  },
  {
    comments: 'hide',
    id: 132,
    link: 'https://grnh.se/9c2fb4393us',
    points: null,
    title: 'CareRev (YC S16) is hiring a senior Android developer',
  },
  {
    comments: '91 comments',
    id: 133,
    link: 'https://amzn.github.io/ion-docs/',
    points: '266 points',
    title: 'Amazon Ion',
  },
  {
    comments: '73 comments',
    id: 134,
    link: 'item?id=23917956',
    points: '98 points',
    title: 'Launch HN: Reploy (YC S20) – Instant fullstack staging environments for web apps',
  },
  {
    comments: '9 comments',
    id: 135,
    link:
      'https://themarket.ch/interview/russell-napier-central-banks-have-become-irrelevant-ld.2323',
    points: '24 points',
    title: 'Central Banks Have Become Irrelevant',
  },
];

export default {
  'GET  /api/items/hackernews': fakeResult,
};
