// eslint-disable-next-line import/no-extraneous-dependencies

const fakeResult = [
  {
    comments: '16 comments',
    is_favorite: 1,
    link: 'http://www.gregegan.net/ESSAYS/GOOGLE/Google.html',
    message_id: 291,
    points: '74 points',
    title: 'Google, the Stupidity Amplifier (2012)',
  },
  {
    comments: 'discuss',
    is_favorite: 0,
    link: 'https://www.pine64.org/2020/08/31/pinephone-manjaro-community-edition/',
    message_id: 290,
    points: '19 points',
    title: 'PinePhone Manjaro Community Edition',
  },
  {
    comments: '85 comments',
    is_favorite: 1,
    link: 'https://backreaction.blogspot.com/2020/08/do-we-really-travel-through-time-with.html',
    message_id: 54,
    points: '174 points',
    title: 'Do we really travel through time with the speed of light?',
  },
  {
    comments: '24 comments',
    is_favorite: 0,
    link: 'https://blog.cloudflare.com/analysis-of-todays-centurylink-level-3-outage/',
    message_id: 53,
    points: '124 points',
    title: "Analysis of Today's CenturyLink/Level(3) Outage",
  },
  {
    comments: '5 comments',
    is_favorite: 0,
    link: 'http://www.openculture.com/2020/08/37-possible-stories.html',
    message_id: 285,
    points: '14 points',
    title: 'The basic dramatic situations, according to 1919 manual for screenwriters',
  },
  {
    comments: '5 comments',
    is_favorite: 0,
    link: 'https://www.edwardtufte.com/bboard/q-and-a-fetch-msg?msg_id=0002yI',
    message_id: 37,
    points: '37 points',
    title: 'Unusual Maps',
  },
  {
    comments: '190 comments',
    is_favorite: 0,
    link: 'https://petersmagnusson.org/2009/09/15/why-are-there-5280-feet-in-a-mile/',
    message_id: 52,
    points: '168 points',
    title: 'Why are there 5280 feet in a mile?',
  },
  {
    comments: '31 comments',
    is_favorite: 0,
    link: 'https://andreaskroepelin.de/blog/sum_types/',
    message_id: 49,
    points: '65 points',
    title: 'Sum Types in Julia and Rust',
  },
  {
    comments: '267 comments',
    is_favorite: 0,
    link:
      'https://www.thedrive.com/the-war-zone/36013/mexican-drug-cartel-now-assassinating-its-enemies-with-improvised-explosive-toting-drones',
    message_id: 50,
    points: '195 points',
    title: 'Drug cartel assassinates its enemies with bomb-toting drones',
  },
  {
    comments: '13 comments',
    is_favorite: 0,
    link:
      'https://arstechnica.com/gadgets/2020/03/ubuntu-20-04s-zsys-adds-zfs-snapshots-to-package-management/',
    message_id: 282,
    points: '23 points',
    title: 'Ubuntu 20.04’s zsys adds ZFS snapshots to package management',
  },
  {
    comments: '6 comments',
    is_favorite: 0,
    link: 'https://mindhive.org/challenges/1273/overview/brief',
    message_id: 279,
    points: '12 points',
    title: 'Alarm as FDA willing to issue Covid-19 vaccine before stringent safety testing',
  },
  {
    comments: '95 comments',
    is_favorite: 0,
    link: 'https://www.attejuvonen.fi/money-out-of-thin-air/',
    message_id: 48,
    points: '135 points',
    title: "Banks create money, but it's less impressive than it sounds",
  },
  {
    comments: '13 comments',
    is_favorite: 0,
    link:
      'https://engineering.mongodb.com/post/we-replaced-an-ssd-with-storage-class-memory-here-is-what-we-learned',
    message_id: 39,
    points: '63 points',
    title: 'We Replaced an SSD with Storage Class Memory',
  },
  {
    comments: 'discuss',
    is_favorite: 0,
    link:
      'https://randomascii.wordpress.com/2020/08/30/the-easy-ones-three-bugs-hiding-in-the-open/',
    message_id: 112,
    points: '17 points',
    title: 'The Easy Ones – Three Bugs Hiding in the Open',
  },
  {
    comments: '7 comments',
    is_favorite: 0,
    link: 'https://douglasduhaime.com/posts/visualizing-tsne-maps-with-three-js.html',
    message_id: 45,
    points: '19 points',
    title: 'Visualizing TSNE Maps with Three.js',
  },
  {
    comments: '43 comments',
    is_favorite: 0,
    link: 'https://nil.wallyjones.com/what-shell-am-i-using/',
    message_id: 41,
    points: '92 points',
    title: 'What Shell Am I Using?',
  },
  {
    comments: '352 comments',
    is_favorite: 0,
    link: 'https://puck.nether.net/pipermail/outages/2020-August/013187.html',
    message_id: 42,
    points: '880 points',
    title: 'Level 3 Global Outage',
  },
  {
    comments: '12 comments',
    is_favorite: 0,
    link: 'https://stitcher.io/blog/dont-get-stuck',
    message_id: 31,
    points: '22 points',
    title: "Don't Get Stuck",
  },
  {
    comments: '25 comments',
    is_favorite: 0,
    link: 'https://k-stash.com',
    message_id: 44,
    points: '42 points',
    title: 'K-Stash: A search engine for your useful links – for devs and researchers',
  },
  {
    comments: '73 comments',
    is_favorite: 0,
    link: 'https://github.com/Droogans/unmaintainable-code/blob/master/README.md',
    message_id: 43,
    points: '135 points',
    title: 'How to Write Unmaintainable Code (2003)',
  },
  {
    comments: '6 comments',
    is_favorite: 0,
    link:
      'https://medium.com/analytics-vidhya/converting-boolean-logic-decision-trees-to-finite-state-machines-180ad195abf2',
    message_id: 35,
    points: '22 points',
    title: 'Converting Boolean-Logic Decision Trees to Finite State Machines',
  },
  {
    comments: '66 comments',
    is_favorite: 0,
    link: 'https://webrtcforthecurious.com/',
    message_id: 38,
    points: '565 points',
    title: 'Show HN: Learn how WebRTC actually works. A book on the protocols, not just APIs',
  },
  {
    comments: '155 comments',
    is_favorite: 0,
    link:
      'https://www.rockpapershotgun.com/2020/08/28/players-are-fixing-microsoft-flight-simulators-missing-monuments-with-google-maps/',
    message_id: 51,
    points: '283 points',
    title: 'Players are fixing Microsoft Flight Simulator’s monuments with Google Maps',
  },
  {
    comments: '28 comments',
    is_favorite: 0,
    link: 'https://www.ctrl.blog/entry/windows-active-hours.html',
    message_id: 26,
    points: '36 points',
    title: 'Win “Active Hours” underscores how you’re not in control of your devices (2016)',
  },
  {
    comments: '24 comments',
    is_favorite: 0,
    link:
      'https://softwarebyscience.com/very-short-functions-are-a-code-smell-an-overview-of-the-science-on-function-length/',
    message_id: 32,
    points: '37 points',
    title: 'An overview of the science on function length',
  },
  {
    comments: '2 comments',
    is_favorite: 0,
    link: 'item?id=24328998',
    message_id: 33,
    points: '35 points',
    title: 'Writing a Lisp to x86-64 compiler',
  },
  {
    comments: '6 comments',
    is_favorite: 0,
    link:
      'https://www.smithsonianmag.com/smithsonian-institution/high-tech-tracking-reveals-birds-movement-beyond-migration-180975673/',
    message_id: 29,
    points: '20 points',
    title: 'High-tech tracking reveals ‘secret world of birds’',
  },
  {
    comments: '73 comments',
    is_favorite: 0,
    link: 'https://cloud.google.com/workflows/docs/reference/syntax',
    message_id: 27,
    points: '81 points',
    title: 'Yml Coding',
  },
  {
    comments: '34 comments',
    is_favorite: 0,
    link: 'http://eopl3.com/',
    message_id: 46,
    points: '203 points',
    title: 'Essentials of Programming Languages',
  },
  {
    comments: '99 comments',
    is_favorite: 0,
    link: 'https://blog.archive.org/2020/08/28/the-legend-of-gayblade/',
    message_id: 47,
    points: '190 points',
    title: 'The Legend of GayBlade',
  },
  {
    comments: '39 comments',
    is_favorite: 0,
    link:
      'https://spectrum.ieee.org/transportation/self-driving/selfdriving-cars-learn-to-read-the-body-language-of-people-on-the-street',
    message_id: 40,
    points: '21 points',
    title: 'Self-driving cars learn to read the body language of people on the street',
  },
  {
    comments: '94 comments',
    is_favorite: 0,
    link:
      'https://eclecticlight.co/2020/08/30/last-week-on-my-mac-is-macos-becoming-unmaintainable/',
    message_id: 36,
    points: '126 points',
    title: 'Is macOS Becoming Unmaintainable?',
  },
  {
    comments: '22 comments',
    is_favorite: 0,
    link: 'https://blog.datawrapper.de/weeklychart-logscale/',
    message_id: 34,
    points: '117 points',
    title: 'How to Read a Log Scale',
  },
  {
    comments: '13 comments',
    is_favorite: 0,
    link:
      'https://www.fastcompany.com/90543500/one-thing-that-the-pandemic-could-be-changing-meeting-lengths',
    message_id: 28,
    points: '22 points',
    title: 'Meeting lengths are changing during coronavirus remote work',
  },
  {
    comments: '363 comments',
    is_favorite: 0,
    link:
      'https://www.forbes.com/sites/robertbryce/2020/08/23/after-48-years-democrats-endorse-nuclear-energy-in-platform/#3c7687df5829',
    message_id: 25,
    points: '459 points',
    title: 'After 48 years, Democrats endorse nuclear energy in platform',
  },
];

export default {
  'GET  /api/items/hackernews': fakeResult,
};
